FROM registry.astralinux.ru/library/astra/ubi18-cpp122:latest

RUN apt-get update && apt-get install -y \
    git \
    libhiredis-dev \
    libpq-dev \
    cmake \
    make \
    g++ \
    redis-tools \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 https://github.com/SergiusTheBest/plog.git /tmp/plog && \
    mv /tmp/plog/include/plog /usr/local/include/plog && \
    rm -rf /tmp/plog


RUN git clone --branch 7.7.0 https://github.com/jtv/libpqxx.git /tmp/libpqxx && \
    cd /tmp/libpqxx && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOC=OFF -DBUILD_TEST=OFF && \
    make -j$(nproc) && make install && \
    cd / && rm -rf /tmp/libpqxx

WORKDIR /app

CMD ["/bin/bash"]